import { hubLabels } from './hub-labels';
import type { PageCard, SourceFact } from './types';
import type { BoundaryNote, FaqItem, TreatmentPage, TreatmentSector } from './treatment-types';

const today = '2026-07-23';

const commonFacts: SourceFact[] = [
  {
    source: 'openspec exploration route map 2026-07-23, extended by Marta copy document 2026-07-31',
    fact: 'Treatment routes live under five sector hubs: the original 29 topics plus six perinatal topics and the adult mood/low-energy topic Marta lists among her motivos de consulta.',
    verified: true
  },
  { source: 'identidad-de-marca/guia-de-marca.md', fact: 'Brand voice is close, professional, precise, non-promissory, and free of unnecessary clinical jargon.', verified: true },
  {
    source: 'Marta copy document "web (1).docx" 2026-07-31',
    fact: 'Method references: careful evaluation, integrative view, person-centred/humanistic work, EMDR (WHO/NICE/ISTSS-backed for trauma), Gestalt, Bioenergetics, and attachment models such as Circle of Security Parenting.',
    verified: true
  }
];

const parentLinks: Record<TreatmentSector, PageCard> = {
  'children-families': { title: hubLabels['children-families'], body: 'El hub reúne las situaciones infantiles y familiares sin convertirlas en etiquetas cerradas.', href: `/areas-de-intervencion/${sectorPath('children-families')}` },
  adolescents: { title: hubLabels.adolescents, body: 'Un mapa para leer adolescencia, autonomía, vínculos, identidad y familia con más calma.', href: `/areas-de-intervencion/${sectorPath('adolescents')}` },
  adults: { title: hubLabels.adults, body: 'Un punto de entrada para ansiedad, estrés, trauma, duelo, vínculos y crecimiento personal.', href: `/areas-de-intervencion/${sectorPath('adults')}` },
  perinatal: { title: hubLabels.perinatal, body: 'Un espacio de cuidado para la fertilidad, el embarazo, el posparto, el vínculo con el bebé y la pérdida gestacional.', href: `/areas-de-intervencion/${sectorPath('perinatal')}` },
  'education-training': { title: hubLabels['education-training'], body: 'Una mirada para unir aprendizaje, emoción, familia, escuela y coordinación cuando hace falta.', href: `/areas-de-intervencion/${sectorPath('education-training')}` }
};

interface Seed {
  sector: TreatmentSector;
  slug: string;
  label: string;
  h1: string;
  title: string;
  description: string;
  summary: string;
  audience: string;
  opening: string;
  signs: string[];
  impact: string;
  help: string;
  process: string;
  faqs: FaqItem[];
  relatedPaths: string[];
  boundaries?: BoundaryNote[];
  group: string;
}

const methodLink = { title: 'Cómo trabajo', body: 'Explico la evaluación cuidadosa, la mirada integradora y el lugar prudente de cada herramienta.', href: '/como-trabajo' };
const localLink = { title: 'Psicología en Ciudad Real', body: 'Un contexto local para valorar encaje sin inventar datos de contacto o dirección.', href: '/psicologia-ciudad-real' };
const contactLink = { title: 'Contacto', body: 'Puedes escribirme con una primera orientación breve, sin contar detalles íntimos de entrada.', href: '/contacto' };
const traumaPillarLink = { title: 'Trauma y duelo en Ciudad Real', body: 'La página local ayuda a distinguir trauma, duelo, EMDR y rutas por etapa vital.', href: '/psicologia-trauma-ciudad-real' };

function page(seed: Seed): TreatmentPage {
  const canonicalPath = `/areas-de-intervencion/${sectorPath(seed.sector)}/${seed.slug}` as const;
  const related = [parentLinks[seed.sector], ...seed.relatedPaths.map((href) => relatedLinkFor(href)), methodLink, localLink, contactLink]
    .filter((item, index, all) => item.href && all.findIndex((candidate) => candidate.href === item.href) === index)
    .slice(0, 6);

  return {
    topicKey: `${seed.sector}:${seed.slug}`,
    canonicalPath,
    sector: seed.sector,
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    h1: seed.h1,
    summary: seed.summary,
    introFirstPerson: seed.opening,
    situations: {
      eyebrow: 'Situaciones frecuentes',
      title: 'Señales que conviene mirar sin etiquetar',
      body: [
        `Puede que ${seed.audience} llegue a consulta con ${list(seed.signs)}. No uso esa información para cerrar un diagnóstico rápido, sino para entender qué está pasando y desde cuándo preocupa.`,
        `También miro qué recursos ya existen alrededor: personas de apoyo, rutinas, escuela, trabajo, familia, cuerpo y momentos en los que el malestar afloja un poco.`
      ]
    },
    contextImpact: {
      eyebrow: 'Vida cotidiana',
      title: 'Por qué puede pesar en el día a día',
      body: [seed.impact, 'Cuando algo empieza a ocupar demasiado espacio, suele afectar a más de una zona. Por eso prefiero ordenar la demanda antes de decidir el camino: a veces el síntoma visible no es el centro del nudo.']
    },
    howICanHelp: {
      eyebrow: 'Cómo puedo acompañarte',
      title: 'Mi forma de trabajar este motivo',
      body: [seed.help, 'Trabajo con una mirada integradora: escucho la historia, el contexto, el cuerpo, los vínculos y las emociones. Si una herramienta concreta puede ayudar, la valoro dentro del proceso, no como una receta universal.']
    },
    process: {
      eyebrow: 'Proceso posible',
      title: 'Qué puede incluir el acompañamiento',
      body: [seed.process, 'El ritmo se revisa contigo. No hay plazos cerrados.'],
      links: [{ label: 'Leer cómo trabajo', href: '/como-trabajo' }, { label: 'Orientar mi consulta', href: '/contacto' }]
    },
    faq: seed.faqs,
    related,
    localCta: 'Si estás en Ciudad Real y quieres valorar si puedo acompañarte, puedes escribirme con una primera orientación breve. No necesitas contarlo todo en el primer mensaje.',
    sourceFacts: commonFacts,
    editorial: { status: 'preview-noindex-needs-human-approval', lastReviewed: today, similarityGroup: seed.group },
    boundaries: seed.boundaries ?? []
  };
}

const baseTreatmentPages = [
  page({
    sector: 'children-families', slug: 'ansiedad-infantil', label: 'Ansiedad infantil', h1: 'Ansiedad infantil', title: 'Ansiedad infantil en Ciudad Real | Hilando Fino Psicología',
    description: 'Acompaño a familias cuando la preocupación, el miedo o la anticipación empiezan a pesar en la vida cotidiana del niño.',
    summary: 'Ansiedad infantil leída con la familia, las rutinas, el colegio, el cuerpo y la necesidad de seguridad del niño.', audience: 'tu hijo o hija', group: 'anxiety-child',
    opening: 'Trabajo la ansiedad infantil mirando al niño y también el entorno que lo sostiene. Me importa comprender cuándo aparece la preocupación, qué la calma y qué respuestas familiares la mantienen sin querer.',
    signs: ['anticipación antes del colegio', 'dolor de barriga sin explicación clara', 'preguntas repetidas para sentirse seguro', 'evitación de planes que antes toleraba'],
    impact: 'En la infancia, la ansiedad puede alterar sueño, comida, juego, separación, aprendizaje y clima familiar. A veces la familia termina organizándose alrededor del miedo, aunque nadie lo haya decidido así.',
    help: 'Te acompaño a traducir la preocupación infantil en necesidades concretas: seguridad, límites, recursos corporales, palabras sencillas y respuestas adultas que no ridiculicen ni refuercen el miedo.',
    process: 'El proceso puede incluir entrevistas familiares, trabajo con el niño mediante lenguaje adaptado, revisión de rutinas, pequeñas exposiciones cuidadas y coordinación escolar si el colegio forma parte del problema.',
    relatedPaths: ['/areas-de-intervencion/infancia-y-familias/miedos-infantiles', '/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil', '/areas-de-intervencion/infancia-y-familias/problemas-de-sueno-infantil'],
    faqs: faq('ansiedad infantil', ['¿Cuándo conviene pedir ayuda?', 'Cuando el miedo empieza a condicionar rutinas, sueño, colegio o vida familiar durante un tiempo sostenido.', '¿Tengo que traer al niño desde el primer día?', 'Depende de la edad y de la situación. A veces primero necesito escuchar a la familia para ordenar la demanda.', '¿Se trabaja solo con el niño?', 'No. En infancia la respuesta adulta es parte del proceso y puede aliviar mucho cuando se ajusta bien.', '¿Y si parece algo físico?', 'Si hay síntomas corporales intensos o nuevos, conviene descartar cuestiones médicas además de mirar la parte emocional.'])
  }),
  page({ sector: 'children-families', slug: 'miedos-infantiles', label: 'Miedos infantiles', h1: 'Miedos infantiles', title: 'Miedos infantiles en Ciudad Real | Hilando Fino Psicología', description: 'Trabajo con familias para comprender el miedo del niño sin ridiculizarlo ni convertirlo automáticamente en diagnóstico.', summary: 'Miedos evolutivos o bloqueantes acompañados con lenguaje claro, respeto y respuesta familiar ajustada.', audience: 'el niño', group: 'fear-child', opening: 'Acompaño miedos infantiles desde una idea sencilla: el miedo no se vence a base de presión ni de burla. Primero necesito entender qué representa para ese niño y qué lugar ocupa en la familia.', signs: ['miedo a dormir solo', 'temor a separarse', 'evitación de lugares concretos', 'necesidad de rituales para sentirse tranquilo'], impact: 'Un miedo que se alarga puede cambiar la hora de dormir, las salidas, la autonomía y la paciencia de todos en casa. También puede generar culpa adulta: exigir demasiado o proteger demasiado.', help: 'Trabajo contigo para distinguir miedo esperable por edad, miedo aprendido, inseguridad relacional y situaciones que necesitan más evaluación. Busco respuestas adultas firmes y cálidas.', process: 'El acompañamiento puede incluir mapa de miedos, lenguaje adaptado, rutinas de seguridad, juego, pequeñas aproximaciones y revisión de cómo reaccionan los adultos ante el miedo.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/ansiedad-infantil', '/areas-de-intervencion/infancia-y-familias/problemas-de-sueno-infantil', '/areas-de-intervencion/infancia-y-familias/separacion-de-los-padres'], faqs: faq('miedos infantiles', ['¿Todos los miedos necesitan terapia?', 'No. Muchos miedos son evolutivos. Pido mirar más cuando bloquean rutinas, generan mucho sufrimiento o se intensifican.', '¿Conviene obligarle a enfrentarse?', 'Forzar suele aumentar inseguridad. Prefiero construir pasos pequeños con presencia adulta.', '¿Puede estar relacionado con cambios familiares?', 'Sí. Mudanzas, pérdidas, separaciones o cambios escolares pueden aparecer como miedo.', '¿Qué puedo hacer en casa?', 'Nombrar el miedo, sostener límites y evitar convertir toda la rutina familiar en una negociación con el miedo.']) }),
  page({ sector: 'children-families', slug: 'regulacion-emocional-infantil', label: 'Regulación emocional infantil', h1: 'Regulación emocional infantil', title: 'Regulación emocional infantil en Ciudad Real | Hilando Fino', description: 'Acompaño a familias para entender rabietas, bloqueos o enfados intensos desde vínculo, límites y contexto.', summary: 'Co-regulación, límites y comprensión de las emociones intensas sin reducirlas a mala conducta.', audience: 'tu hijo o hija', group: 'regulation-child', opening: 'Trabajo la regulación emocional infantil ayudando a los adultos a leer qué hay debajo de una reacción intensa. Una rabieta no es solo ruido: puede hablar de cansancio, frustración, miedo, necesidad de límite o dificultad para poner palabras.', signs: ['rabietas muy largas', 'bloqueos ante cambios', 'enfados desproporcionados', 'dificultad para calmarse incluso con ayuda'], impact: 'Cuando la emoción desborda, la casa puede girar alrededor de evitar explosiones. El colegio también puede interpretar la reacción como desobediencia si no se entiende el contexto.', help: 'Te acompaño a construir co-regulación: presencia, límites claros, lenguaje emocional, rutinas y formas de reparar después del conflicto sin culpabilizar.', process: 'Podemos revisar detonantes, respuestas adultas, sueño, exigencia, juego, escuela y necesidades de apego. El objetivo es que la familia tenga más recursos antes, durante y después del desborde.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/problemas-de-conducta-infantil', '/areas-de-intervencion/infancia-y-familias/autoestima-infantil', '/areas-de-intervencion/adolescentes/regulacion-emocional-adolescente'], faqs: faq('regulación emocional infantil', ['¿Una rabieta intensa significa un trastorno?', 'No necesariamente. Prefiero mirar frecuencia, duración, contexto, edad y recursos disponibles.', '¿Poner límites empeora el vínculo?', 'No si el límite se sostiene con claridad y presencia. Límite y vínculo no son opuestos.', '¿Debe participar el colegio?', 'Puede ayudar si las reacciones aparecen allí o si necesitamos coherencia entre casa y aula.', '¿Se puede trabajar sin culpar a la familia?', 'Sí. La idea es comprender patrones y abrir alternativas, no señalar culpables.']) }),
  page({ sector: 'children-families', slug: 'problemas-de-conducta-infantil', label: 'Problemas de conducta infantil', h1: 'Problemas de conducta infantil', title: 'Problemas de conducta infantil en Ciudad Real | Hilando Fino', description: 'Miro la conducta como una señal dentro de una historia, un vínculo y un contexto, no como una etiqueta aislada.', summary: 'Conducta infantil comprendida como comunicación dentro de casa, colegio, vínculo y etapa evolutiva.', audience: 'la familia', group: 'behavior-child', opening: 'Acompaño problemas de conducta infantil sin partir de que el niño “se porta mal” porque sí. Me interesa saber qué comunica esa conducta, cuándo aparece y qué necesita el sistema familiar para responder de otra manera.', signs: ['desafíos constantes', 'peleas en casa', 'avisos repetidos desde el colegio', 'rechazo de normas básicas'], impact: 'La conducta difícil puede desgastar el vínculo, generar etiquetas en el aula y dejar a los adultos atrapados entre castigar, ceder o agotarse.', help: 'Trabajo contigo para observar función, contexto y respuesta adulta. Busco límites comprensibles, reparación, coordinación y una lectura emocional que no quite responsabilidad, pero tampoco humille.', process: 'El proceso puede incluir entrevistas familiares, análisis de situaciones concretas, pautas realistas, coordinación escolar y revisión de cómo se sostiene el límite sin convertirlo todo en lucha.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil', '/areas-de-intervencion/infancia-y-familias/dificultades-escolares', '/areas-de-intervencion/orientacion-educativa-y-formacion/asesoramiento-familiar'], faqs: faq('conducta infantil', ['¿Es falta de disciplina?', 'A veces hay límites poco claros, pero también puede haber emoción, cansancio, inseguridad o contexto escolar.', '¿Trabajo con padres o con el niño?', 'Normalmente necesito mirar ambos niveles, ajustándolo a la edad y al motivo.', '¿Se dan pautas concretas?', 'Sí, cuando tienen sentido, pero no como recetas aisladas de la historia familiar.', '¿Y si el colegio está preocupado?', 'Podemos valorar coordinación, siempre cuidando consentimiento y privacidad.']) }),
  page({ sector: 'children-families', slug: 'dificultades-escolares', label: 'Dificultades escolares', h1: 'Dificultades escolares', title: 'Dificultades escolares en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño cuando el colegio empieza a ser fuente de malestar, bloqueo, conflicto o pérdida de confianza.', summary: 'Malestar escolar, aprendizaje, emoción y relaciones mirados con la familia y el centro cuando procede.', audience: 'el colegio', group: 'school-child', opening: 'Trabajo las dificultades escolares sin reducirlas a notas. Cuando el colegio se vuelve un lugar de tensión, conviene mirar aprendizaje, emoción, relaciones, autoestima y expectativas adultas.', signs: ['rechazo a ir a clase', 'bajada de confianza', 'bloqueo con tareas', 'conflictos con compañeros o docentes'], impact: 'La escuela ocupa muchas horas de la vida infantil. Si allí aparece malestar, puede afectar al descanso, al juego, a la relación con la familia y a la forma en que el niño se mira a sí mismo.', help: 'Te acompaño a ordenar hipótesis: qué pertenece al aprendizaje, qué a la emoción, qué a la dinámica escolar y qué puede necesitar valoración específica o coordinación.', process: 'Puede incluir entrevistas familiares, lectura de informes si existen, contacto con el centro con consentimiento y estrategias para que el niño recupere seguridad sin presión excesiva.', relatedPaths: ['/areas-de-intervencion/orientacion-educativa-y-formacion/dificultades-de-aprendizaje', '/areas-de-intervencion/orientacion-educativa-y-formacion/coordinacion-centros-educativos', '/areas-de-intervencion/infancia-y-familias/autoestima-infantil'], faqs: faq('dificultades escolares', ['¿Es un problema emocional o de aprendizaje?', 'A veces ambas cosas se mezclan. Por eso conviene ordenar antes de etiquetar.', '¿Puedo consultar si no hay diagnóstico?', 'Sí. La consulta puede ayudar a entender el impacto y decidir si hace falta derivación o evaluación específica.', '¿Se habla con el colegio?', 'Solo cuando ayuda y con consentimiento. La coordinación debe tener un objetivo claro.', '¿Qué pasa si mi hijo se siente torpe?', 'Trabajo también la autoestima y la narrativa que se construye alrededor del rendimiento.']) }),
  page({ sector: 'children-families', slug: 'trauma-y-duelo-infantil', label: 'Trauma y duelo infantil', h1: 'Trauma y duelo infantil', title: 'Trauma y duelo infantil en Ciudad Real | Hilando Fino', description: 'Acompaño a familias cuando una pérdida o experiencia difícil necesita palabras claras, ritmo y presencia adulta segura.', summary: 'Trauma y duelo infantil con lenguaje adaptado, presencia adulta, escuela y seguridad emocional.', audience: 'un niño', group: 'trauma-grief-child', opening: 'Acompaño trauma y duelo infantil cuidando mucho el lenguaje. En la infancia, una pérdida o una experiencia difícil necesita adultos que pongan palabras, sostengan rutinas y no exijan una forma única de sentir.', signs: ['juego repetitivo sobre lo ocurrido', 'miedos nuevos', 'cambios de sueño o conducta', 'preguntas que vuelven una y otra vez'], impact: 'El duelo infantil puede aparecer en el cuerpo, el juego, el colegio o la conducta. A veces el adulto espera tristeza visible y se encuentra con rabia, silencio o aparente normalidad.', help: 'Te acompaño a explicar sin ocultar ni invadir, a sostener presencia adulta y a valorar qué necesita el niño según edad, vínculo, historia y recursos familiares.', process: 'El proceso puede incluir trabajo con cuidadores, sesiones adaptadas al niño, coordinación escolar y revisión de seguridad. Si aparece riesgo o sintomatología intensa, valoro derivación o apoyo adicional.', relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/infancia-y-familias/separacion-de-los-padres', '/areas-de-intervencion/adolescentes/duelo-adolescente'], boundaries: [{ kind: 'emergency', text: 'Si hay riesgo inmediato, violencia o desprotección, la prioridad son los servicios de emergencia o protección correspondientes.' }], faqs: faq('trauma y duelo infantil', ['¿Cuándo conviene pedir ayuda?', 'Cuando la pérdida bloquea sueño, colegio o juego durante semanas, o cuando la familia no encuentra cómo sostenerlo.', '¿Y si no quiere hablar?', 'Puede expresar lo que vive jugando, con el cuerpo o con conducta. No siempre empieza por palabras.', '¿El duelo infantil es igual que el adulto?', 'No. Depende del desarrollo, del vínculo y de cómo los adultos sostienen la pérdida.', '¿Puede necesitar ayuda el adulto cuidador?', 'Sí. Acompañar a un niño en duelo también requiere sostener a quien cuida.']) }),
  page({ sector: 'children-families', slug: 'separacion-de-los-padres', label: 'Separación de los padres', h1: 'Separación de los padres', title: 'Separación de los padres y niños en Ciudad Real | Hilando Fino', description: 'Acompaño a familias para cuidar la comunicación y la seguridad emocional de los hijos durante una separación.', summary: 'Acompañamiento emocional a hijos y familia durante separación, sin sustituir asesoramiento legal.', audience: 'la familia', group: 'separation-child', opening: 'Acompaño separaciones familiares desde el lugar de los hijos. No trabajo para buscar culpables, sino para cuidar lenguaje, rutinas, transiciones y seguridad emocional en un momento sensible.', signs: ['cambios de conducta tras la separación', 'preguntas difíciles', 'lealtades divididas', 'rechazo de alguna transición'], impact: 'Una separación puede remover sueño, escuela, enfados, culpa o miedo a perder a un progenitor. También puede poner a los adultos bajo tanta tensión que cuesta separar conflicto de cuidado.', help: 'Te acompaño a pensar qué decir, qué evitar, cómo sostener límites y cómo cuidar que el niño no quede en medio de conversaciones adultas.', process: 'El proceso puede incluir orientación a progenitores, sesiones familiares cuando encaja y pautas de comunicación. No sustituyo mediación, asesoramiento legal ni decisiones judiciales.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/trauma-y-duelo-infantil', '/areas-de-intervencion/infancia-y-familias/problemas-de-conducta-infantil', '/areas-de-intervencion/orientacion-educativa-y-formacion/asesoramiento-familiar'], boundaries: [{ kind: 'legal', text: 'Esta orientación psicológica no sustituye asesoramiento legal.' }], faqs: faq('separación de los padres', ['¿Cómo se lo contamos?', 'Con frases claras, acordes a la edad y sin cargar al niño con detalles del conflicto adulto.', '¿Y si cambia su conducta?', 'Puede ser una forma de expresar inseguridad, rabia o tristeza. Conviene mirar contexto y duración.', '¿Puede venir solo un progenitor?', 'Depende del objetivo y del encuadre. Cuidar la posición de los hijos es central.', '¿Se trabaja la coparentalidad?', 'Puedo orientar comunicación y necesidades emocionales, sin asumir funciones legales o de mediación no confirmadas.']) }),
  page({ sector: 'children-families', slug: 'autoestima-infantil', label: 'Autoestima infantil', h1: 'Autoestima infantil', title: 'Autoestima infantil en Ciudad Real | Hilando Fino Psicología', description: 'Trabajo la autoestima infantil mirando la mirada recibida, las experiencias de logro, los límites y la forma de narrarse.', summary: 'Autoestima infantil construida en familia, escuela, logro, error, límites y relato propio.', audience: 'tu hijo o hija', group: 'self-esteem-child', opening: 'Trabajo la autoestima infantil mirando cómo se está construyendo la mirada del niño sobre sí mismo. No se trata de repetir elogios, sino de comprender qué experiencias le hacen sentirse capaz, querido y valioso.', signs: ['miedo intenso a equivocarse', 'comparación con otros niños', 'frases de incapacidad', 'evitación de retos por vergüenza'], impact: 'La autoestima infantil puede influir en el aprendizaje, el juego, las relaciones y la tolerancia al error. Cuando baja, el niño puede dejar de intentar antes incluso de saber si puede.', help: 'Te acompaño a revisar mensajes familiares, experiencias escolares, límites, autonomía y formas de reparar errores para que la confianza no dependa solo del resultado.', process: 'El proceso puede combinar trabajo con el niño, orientación familiar y coordinación escolar si la vivencia de incapacidad aparece en el aula.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/dificultades-escolares', '/areas-de-intervencion/adolescentes/autoestima-adolescente', '/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil'], faqs: faq('autoestima infantil', ['¿Decirle que todo lo hace bien ayuda?', 'Puede aliviar un momento, pero no construye confianza real si no hay experiencias de logro y aceptación del error.', '¿La autoestima depende de la escuela?', 'La escuela influye mucho, aunque no es el único lugar donde se forma la mirada propia.', '¿Y si evita todo lo nuevo?', 'Conviene mirar miedo al error, exigencia, comparación y experiencias previas.', '¿Cómo participa la familia?', 'La familia puede ajustar lenguaje, límites, autonomía y formas de acompañar el fracaso.']) }),
  page({ sector: 'children-families', slug: 'problemas-de-sueno-infantil', label: 'Problemas de sueño infantil', h1: 'Problemas de sueño infantil', title: 'Problemas de sueño infantil en Ciudad Real | Hilando Fino', description: 'Acompaño a familias cuando el sueño se cruza con miedo, rutinas, seguridad y activación emocional.', summary: 'Sueño infantil visto desde rutinas, seguridad, miedo, separación y límites, con frontera pediátrica clara.', audience: 'el sueño de tu hijo o hija', group: 'sleep-child', opening: 'Acompaño problemas de sueño infantil cuando la noche se vuelve un momento de tensión para toda la familia. Miro rutinas, miedo, separación, activación y seguridad sin convertir la cama en una batalla.', signs: ['dificultad para conciliar', 'despertares con miedo', 'necesidad constante de compañía', 'cansancio que afecta al colegio o al juego'], impact: 'Dormir mal puede cambiar el humor, la atención, la paciencia familiar y la sensación de seguridad. También puede hacer que los adultos lleguen agotados y con menos recursos.', help: 'Te acompaño a ordenar qué parte es rutina, qué parte es miedo, qué parte es desarrollo y qué señales conviene consultar con pediatría.', process: 'El proceso puede incluir registro de rutinas, ajuste gradual de hábitos, trabajo con miedos, apoyo familiar y derivación médica si aparecen síntomas físicos o dudas evolutivas.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/miedos-infantiles', '/areas-de-intervencion/infancia-y-familias/ansiedad-infantil', '/areas-de-intervencion/infancia-y-familias/control-de-esfinteres'], boundaries: [{ kind: 'pediatric', text: 'Si hay ronquidos intensos, pausas respiratorias, dolor, fiebre, medicación o dudas de desarrollo, la valoración pediátrica es prioritaria.' }], faqs: faq('sueño infantil', ['¿Es psicológico todo problema de sueño?', 'No. Por eso pregunto por salud, desarrollo y señales que requieren pediatría.', '¿Hay que dejarle llorar?', 'No trabajo desde recetas universales. Busco pasos que cuiden vínculo, límite y descanso.', '¿Puede relacionarse con ansiedad?', 'Sí. Miedo, separación o anticipación pueden aparecer por la noche.', '¿Cuándo consultar?', 'Cuando el sueño afecta al bienestar del niño o de la familia de forma sostenida.']) }),
  page({ sector: 'children-families', slug: 'control-de-esfinteres', label: 'Control de esfínteres', h1: 'Control de esfínteres', title: 'Control de esfínteres en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño el control de esfínteres con respeto al desarrollo, sin presión, vergüenza ni lecturas simplistas.', summary: 'Acompañamiento respetuoso de enuresis, encopresis o dificultad evolutiva con frontera médica.', audience: 'el control de esfínteres', group: 'toilet-child', opening: 'Acompaño dificultades en el control de esfínteres con mucho cuidado, porque la vergüenza y la presión suelen empeorar lo que ya pesa. Primero miro desarrollo, salud, contexto y vivencia emocional.', signs: ['escapes que generan vergüenza', 'miedo a ir al baño', 'retrocesos tras cambios familiares', 'tensión entre escuela y casa'], impact: 'Estas dificultades pueden afectar autoestima, vida escolar, sueño, autonomía y relación con los adultos. También pueden convertirse en un tema de conflicto cotidiano.', help: 'Te acompaño a retirar culpa, ordenar rutinas, cuidar el lenguaje y valorar cuándo hace falta apoyo pediátrico u otra evaluación.', process: 'Podemos revisar la historia evolutiva, momentos de cambio, respuesta adulta, colegio y señales corporales. Proceso respetuoso y coordinado.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/problemas-de-sueno-infantil', '/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil', '/areas-de-intervencion/infancia-y-familias/autoestima-infantil'], boundaries: [{ kind: 'medical', text: 'Antes de atribuirlo a emoción, conviene descartar causas médicas o evolutivas cuando hay dolor, infección, estreñimiento, cambios bruscos o señales físicas.' }], faqs: faq('control de esfínteres', ['¿Es cuestión de voluntad?', 'No lo reduzco a voluntad. Puede haber desarrollo, cuerpo, emoción, rutina y presión.', '¿Reñir ayuda?', 'Normalmente aumenta vergüenza y tensión. Prefiero lenguaje claro y respetuoso.', '¿Puede aparecer tras un cambio?', 'Sí. Separaciones, pérdidas, colegio o estrés familiar pueden influir.', '¿Cuándo consultar al pediatra?', 'Ante dolor, estreñimiento, infecciones, cambios bruscos o dudas de maduración.']) }),
  page({ sector: 'adolescents', slug: 'autoestima-adolescente', label: 'Autoestima adolescencia', h1: 'Autoestima en adolescentes', title: 'Autoestima en adolescentes en Ciudad Real | Hilando Fino', description: 'Acompaño procesos de autoestima adolescente cuando cuerpo, grupo, exigencia e identidad se mezclan.', summary: 'Autoestima adolescente diferenciada por cuerpo, comparación, pertenencia, identidad y confidencialidad.', audience: 'un adolescente', group: 'self-esteem-teen', opening: 'Trabajo la autoestima en adolescentes sin tratarla como una frase motivacional. En esta etapa, cuerpo, grupo, redes, estudios, identidad y familia se mezclan con mucha intensidad.', signs: ['comparación constante', 'vergüenza corporal', 'miedo a quedar fuera del grupo', 'autoexigencia que bloquea'], impact: 'Una autoestima frágil puede afectar amistades, decisiones académicas, expresión emocional y relación con la familia. A veces se oculta detrás de ironía, aislamiento o aparente indiferencia.', help: 'Te acompaño a crear un espacio donde el adolescente pueda hablar sin sentirse invadido y donde la familia pueda apoyar sin convertir cada conversación en interrogatorio.', process: 'El proceso puede incluir sesiones individuales, acuerdos de confidencialidad adecuados a la edad, momentos con la familia y trabajo sobre comparación, límites y relato propio.', relatedPaths: ['/areas-de-intervencion/adolescentes/identidad-adolescente', '/areas-de-intervencion/adolescentes/relaciones-sociales-adolescencia', '/areas-de-intervencion/adolescentes/ansiedad-adolescente'], faqs: faq('autoestima adolescente', ['¿La familia participa?', 'Sí cuando ayuda, cuidando la privacidad y el encuadre del adolescente.', '¿Es normal compararse tanto?', 'La comparación es frecuente, pero conviene mirar cuándo domina la vida y deteriora la confianza.', '¿Se trabaja imagen corporal?', 'Puedo acompañar la vivencia corporal sin hacer promesas ni sustituir valoración médica cuando corresponde.', '¿Y si no quiere venir?', 'Necesito valorar motivación y consentimiento. Forzar puede dañar la alianza.']) }),
  page({ sector: 'adolescents', slug: 'ansiedad-adolescente', label: 'Ansiedad adolescentes', h1: 'Ansiedad en adolescentes', title: 'Ansiedad en adolescentes en Ciudad Real | Hilando Fino', description: 'Trabajo la ansiedad adolescente escuchando estudios, vínculos, cuerpo, decisiones y necesidad de autonomía.', summary: 'Ansiedad adolescente ligada a estudio, grupo, cuerpo, futuro, autonomía y relación familiar.', audience: 'la ansiedad adolescente', group: 'anxiety-teen', opening: 'Acompaño ansiedad en adolescentes entendiendo que no se expresa igual que en la infancia ni en la vida adulta. Puede aparecer en el cuerpo, los estudios, el grupo, las decisiones o el miedo a fallar.', signs: ['bloqueos ante exámenes', 'evitación social', 'irritabilidad antes de planes', 'sensación corporal de alarma'], impact: 'La ansiedad puede estrechar la vida adolescente: menos planes, más control, más discusiones familiares y más dificultad para imaginar futuro con calma.', help: 'Trabajo con el adolescente para entender la alarma y construir recursos; con la familia, cuando procede, busco acompañar sin invadir ni convertir cada síntoma en vigilancia.', process: 'El proceso puede incluir evaluación, recursos corporales, exposición gradual, trabajo con pensamientos, revisión de exigencia y coordinación académica si el contexto educativo pesa mucho.', relatedPaths: ['/areas-de-intervencion/adolescentes/autoestima-adolescente', '/areas-de-intervencion/adolescentes/orientacion-academica-adolescentes', '/areas-de-intervencion/adultos/ansiedad'], faqs: faq('ansiedad adolescente', ['¿Cómo se diferencia de nervios normales?', 'Miro intensidad, duración, evitación e impacto en vida social, estudio, sueño o familia.', '¿Tiene que hablar la familia?', 'Puede ayudar, pero cuido que el adolescente tenga un espacio propio.', '¿Y si hay ataques de pánico?', 'Conviene evaluar bien síntomas, contexto y seguridad; no lo reduzco a una etiqueta rápida.', '¿Puede afectar a los estudios?', 'Sí. La ansiedad puede bloquear rendimiento aunque haya capacidad.']) }),
  page({ sector: 'adolescents', slug: 'relaciones-sociales-adolescencia', label: 'Relaciones sociales', h1: 'Relaciones sociales en la adolescencia', title: 'Relaciones sociales adolescentes en Ciudad Real | Hilando Fino', description: 'Acompaño dificultades con amistades, pertenencia, conflicto o aislamiento desde escucha y cuidado del vínculo.', summary: 'Amistades, pertenencia, conflicto, aislamiento, bullying y familia sin convertirlo en disciplina escolar.', audience: 'una dificultad en las relaciones sociales', group: 'social-teen', opening: 'Acompaño dificultades en relaciones sociales adolescentes escuchando qué significa pertenecer, quedarse fuera, discutir, callar o sentirse observado. Para un adulto puede parecer pequeño; para un adolescente puede ocuparlo todo.', signs: ['aislamiento doloroso', 'conflictos repetidos con amistades', 'miedo a exponerse', 'cambios bruscos tras problemas de grupo'], impact: 'El grupo adolescente influye en autoestima, identidad, sueño, estudio y estado de ánimo. Una dificultad relacional puede vivirse como pérdida de lugar.', help: 'Trabajo habilidades, emoción, límites y lectura del vínculo sin culpabilizar al adolescente ni simplificarlo como “timidez” o “drama”.', process: 'El proceso puede incluir exploración de vínculos, recursos de comunicación, trabajo con vergüenza o rabia y participación familiar si hay aislamiento, acoso o preocupación de seguridad.', relatedPaths: ['/areas-de-intervencion/adolescentes/autoestima-adolescente', '/areas-de-intervencion/adolescentes/identidad-adolescente', '/areas-de-intervencion/adolescentes/ansiedad-adolescente'], boundaries: [{ kind: 'safety', text: 'Si hay acoso, amenazas, violencia o riesgo de autolesión, la prioridad es activar protección adulta y recursos adecuados.' }], faqs: faq('relaciones sociales adolescentes', ['¿El aislamiento siempre es problema?', 'No siempre. Miro si es elegido, doloroso, reciente o asociado a miedo y pérdida de bienestar.', '¿Se trabaja habilidades sociales?', 'Sí cuando ayuda, pero también miro autoestima, vergüenza, vínculo y contexto.', '¿Qué pasa si hay bullying?', 'No lo trato como un problema individual. Necesita protección adulta y coordinación.', '¿La familia debe intervenir?', 'A veces sí, pero con cuidado para no invadir ni aumentar exposición.']) }),
  page({ sector: 'adolescents', slug: 'identidad-adolescente', label: 'Identidad', h1: 'Identidad en adolescentes', title: 'Identidad en adolescentes en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño dudas, cambios y preguntas sobre identidad con respeto, escucha y un espacio seguro.', summary: 'Exploración de identidad, cuerpo, pertenencia, futuro y conversación familiar con prudencia.', audience: 'una pregunta de identidad', group: 'identity-teen', opening: 'Acompaño preguntas de identidad en adolescencia con respeto y prudencia. No fuerzo respuestas ni convierto cada duda en problema; abro un espacio para escuchar qué necesita ser pensado.', signs: ['cambios en la forma de presentarse', 'dudas sobre futuro o pertenencia', 'tensión entre autonomía y familia', 'miedo a no ser aceptado'], impact: 'La identidad se juega en el cuerpo, el grupo, la familia, los estudios y la imagen de futuro. Cuando no hay espacio para hablar, puede aparecer aislamiento o conflicto.', help: 'Te acompaño a sostener preguntas con cuidado, diferenciando exploración, sufrimiento, presión externa y necesidades de seguridad.', process: 'El proceso puede incluir conversación individual, trabajo con familia si procede y construcción de un lenguaje que no invada ni niegue la experiencia adolescente.', relatedPaths: ['/areas-de-intervencion/adolescentes/autoestima-adolescente', '/areas-de-intervencion/adolescentes/relaciones-sociales-adolescencia', '/areas-de-intervencion/adolescentes/orientacion-academica-adolescentes'], boundaries: [{ kind: 'scope', text: 'No hago afirmaciones sobre especializaciones no verificadas; si una situación requiere recursos específicos, lo valoro y derivo cuando corresponde.' }], faqs: faq('identidad adolescente', ['¿Es normal dudar tanto?', 'La adolescencia abre muchas preguntas. Miro si hay sufrimiento, presión o falta de apoyo.', '¿La familia participa?', 'Cuando ayuda y con un encuadre respetuoso. No todo debe convertirse en debate familiar.', '¿Se dan respuestas cerradas?', 'No. Trabajo para que el adolescente pueda escucharse y cuidarse mejor.', '¿Y si hay rechazo familiar?', 'La prioridad es seguridad, comunicación cuidadosa y apoyo adecuado.']) }),
  page({ sector: 'adolescents', slug: 'orientacion-academica-adolescentes', label: 'Orientación académica', h1: 'Orientación académica en adolescentes', title: 'Orientación académica adolescentes en Ciudad Real | Hilando Fino', description: 'Acompaño decisiones académicas mirando intereses, capacidades, presión externa y momento vital.', summary: 'Decisiones académicas adolescentes con presión, miedo, capacidades, expectativas y futuro.', audience: 'una decisión académica', group: 'academic-teen', opening: 'Acompaño orientación académica en adolescentes cuando decidir se vuelve una fuente de presión. No miro solo notas: también intereses, miedo a fallar, expectativas familiares, cansancio y momento vital.', signs: ['bloqueo al elegir itinerario', 'angustia ante exámenes', 'desmotivación persistente', 'conflicto familiar por expectativas'], impact: 'Una decisión académica puede sentirse como una decisión sobre la identidad completa. Si se vive con miedo, puede activar ansiedad, evitación o discusiones.', help: 'Trabajo para ordenar variables y devolver capacidad de decisión: qué le interesa, qué se le da bien, qué presión recibe y qué apoyos necesita.', process: 'El proceso puede incluir entrevistas, revisión de historia escolar, valores, recursos, conversaciones familiares y coordinación educativa si aporta claridad.', relatedPaths: ['/areas-de-intervencion/adolescentes/ansiedad-adolescente', '/areas-de-intervencion/adolescentes/identidad-adolescente', '/areas-de-intervencion/orientacion-educativa-y-formacion/coordinacion-centros-educativos'], faqs: faq('orientación académica adolescente', ['¿Es orientación vocacional?', 'Puede incluir decisiones vocacionales, pero también emoción, presión y contexto.', '¿Se hacen pruebas?', 'No afirmo pruebas o informes no confirmados. Valoro qué recursos son adecuados en cada caso.', '¿Puede participar la familia?', 'Sí, especialmente cuando expectativas y comunicación están influyendo.', '¿Y si no sabe qué quiere?', 'No siempre hay una respuesta inmediata. Se puede trabajar el bloqueo y abrir criterios.']) }),
  page({ sector: 'adolescents', slug: 'trauma-adolescente', label: 'Trauma adolescencia', h1: 'Trauma en adolescentes', title: 'Trauma en adolescentes en Ciudad Real | Hilando Fino', description: 'Acompaño experiencias difíciles en adolescencia con evaluación prudente, seguridad y ritmo.', summary: 'Trauma adolescente con autonomía, consentimiento, familia, seguridad y posible EMDR tras evaluación.', audience: 'un adolescente', group: 'trauma-teen', opening: 'Acompaño trauma en adolescentes cuidando seguridad, ritmo y consentimiento. En esta etapa puede haber una tensión delicada entre necesitar apoyo y no querer sentirse invadido.', signs: ['evitación de recuerdos o lugares', 'reactividad intensa', 'desconexión emocional', 'cambios bruscos en confianza o conducta'], impact: 'Una experiencia difícil puede afectar estudio, cuerpo, relaciones, sueño y autonomía. También puede cambiar la relación con la familia si el adolescente siente que nadie entiende su ritmo.', help: 'Trabajo primero para comprender qué ocurrió, qué recursos tiene y qué necesita para sentirse seguro. EMDR u otras herramientas solo tienen sentido si la evaluación lo indica.', process: 'El proceso puede incluir estabilización, recursos corporales, acuerdos de confidencialidad, participación familiar medida y coordinación si hay riesgo o contexto escolar implicado.', relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/adolescentes/duelo-adolescente', '/areas-de-intervencion/adultos/trauma'], boundaries: [{ kind: 'emergency', text: 'Si hay riesgo, violencia, abuso activo o autolesión, la prioridad es protección y recursos de emergencia.' }], faqs: faq('trauma adolescente', ['¿Tiene que contarlo todo?', 'No. En trauma no empujo el relato. Primero seguridad y recursos.', '¿Puede hacerse EMDR?', 'Solo si la evaluación lo aconseja y hay estabilidad suficiente. No es una obligación.', '¿Qué papel tiene la familia?', 'Puede sostener, pero el adolescente necesita un espacio propio y seguro.', '¿Y si no quiere venir?', 'Sin una mínima colaboración, conviene valorar cómo abrir apoyo sin forzar.']) }),
  page({ sector: 'adolescents', slug: 'duelo-adolescente', label: 'Duelo adolescencia', h1: 'Duelo en adolescentes', title: 'Duelo en adolescentes en Ciudad Real | Hilando Fino', description: 'Acompaño pérdidas en adolescencia respetando silencio, rabia, cambios de ánimo y necesidad de seguir viviendo lo cotidiano.', summary: 'Duelo adolescente entre pérdida, grupo, colegio, silencio, rabia, autonomía y apoyo familiar.', audience: 'un duelo adolescente', group: 'grief-teen', opening: 'Acompaño duelo en adolescentes sin imponer una forma correcta de vivir la pérdida. Puede haber silencio, rabia, necesidad de normalidad, culpa o una mezcla que cambia rápido.', signs: ['aislamiento tras la pérdida', 'rabia o irritabilidad', 'bajada escolar', 'culpa por seguir haciendo vida normal'], impact: 'El duelo adolescente ocurre mientras la vida social, el estudio y la identidad siguen moviéndose. Esa mezcla puede hacer que parezca que no le importa o que todo le supera.', help: 'Trabajo para dar un espacio propio al dolor y también para orientar a la familia sobre cómo estar cerca sin perseguir ni abandonar.', process: 'El proceso puede incluir lenguaje de duelo, recursos emocionales, conversación familiar, coordinación escolar si ayuda y cuidado del vínculo con la persona perdida.', relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/adolescentes/trauma-adolescente', '/areas-de-intervencion/adolescentes/regulacion-emocional-adolescente'], faqs: faq('duelo adolescente', ['¿Es normal que no quiera hablar?', 'Sí puede serlo. Miro si el silencio protege, bloquea o es la única forma posible ahora.', '¿Debe seguir con rutinas?', 'Las rutinas pueden sostener, pero no deben usarse para negar el dolor.', '¿Puede aparecer enfado?', 'Sí. La rabia es frecuente y necesita un lugar seguro.', '¿Cuándo preocupa?', 'Cuando hay riesgo, aislamiento extremo, consumo, autolesión o deterioro sostenido.']) }),
  page({ sector: 'adolescents', slug: 'regulacion-emocional-adolescente', label: 'Regulación emocional adolescencia', h1: 'Regulación emocional en adolescentes', title: 'Regulación emocional adolescentes en Ciudad Real | Hilando Fino', description: 'Trabajo la regulación emocional adolescente combinando comprensión, límites, cuerpo, vínculo y recursos sostenibles.', summary: 'Regulación adolescente con autonomía, límites, cuerpo, familia y recursos practicables fuera de sesión.', audience: 'la regulación emocional adolescente', group: 'regulation-teen', opening: 'Trabajo la regulación emocional en adolescentes respetando que la intensidad no se resuelve solo con “calmarse”. Hay cuerpo, vínculo, identidad, límites y necesidad de autonomía.', signs: ['estallidos emocionales', 'bloqueos o desconexión', 'cambios rápidos de ánimo', 'discusiones familiares que escalan'], impact: 'Cuando la emoción sube demasiado, puede afectar relaciones, estudio, sueño, decisiones y convivencia. La familia suele quedar atrapada entre controlar y retirarse.', help: 'Te acompaño a construir recursos sostenibles: poner palabras, leer el cuerpo, anticipar detonantes, reparar después y sostener límites sin romper el vínculo.', process: 'El proceso puede alternar espacio individual, momentos familiares y prácticas concretas para que lo trabajado no se quede solo en consulta.', relatedPaths: ['/areas-de-intervencion/adolescentes/ansiedad-adolescente', '/areas-de-intervencion/adolescentes/relaciones-sociales-adolescencia', '/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil'], faqs: faq('regulación emocional adolescente', ['¿Es solo cosa de la edad?', 'La adolescencia trae intensidad, pero miro impacto, sufrimiento y recursos disponibles.', '¿Qué puede hacer la familia?', 'Sostener límites claros, escuchar sin invadir y revisar cómo escalan los conflictos.', '¿Se enseñan técnicas?', 'Sí, si encajan; pero las técnicas necesitan contexto y práctica.', '¿Y si hay autolesión?', 'Requiere valoración específica y recursos de seguridad. No se aborda como una rabieta.']) }),
  page({ sector: 'adults', slug: 'ansiedad', label: 'Ansiedad adultos', h1: 'Ansiedad en adultos', title: 'Ansiedad en adultos en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño la ansiedad en adultos mirando alarma, exigencia, historia personal, cuerpo y contexto actual.', summary: 'Ansiedad adulta diferenciada por alarma, control, cuerpo, responsabilidad, historia y contexto presente.', audience: 'la ansiedad', group: 'anxiety-adult', opening: 'Acompaño la ansiedad en adultos empezando por comprender qué intenta decir esa alarma. No la trato como un enemigo aislado: miro cuerpo, exigencia, historia, responsabilidad y contexto actual.', signs: ['preocupación constante', 'tensión corporal', 'necesidad de control', 'evitación de decisiones o lugares'], impact: 'La ansiedad puede estrechar la vida: se planifica todo para evitar malestar, se descansa peor y las relaciones se llenan de anticipación o irritabilidad.', help: 'Trabajo contigo para entender disparadores, mantenimiento y recursos. Busco que puedas relacionarte de otro modo con la alarma, no solo taparla.', process: 'El proceso puede incluir evaluación, psicoeducación clara, trabajo corporal, revisión de creencias, exposición gradual y exploración de historia personal si tiene sentido.', relatedPaths: ['/areas-de-intervencion/adultos/estres', '/areas-de-intervencion/adultos/trauma', '/areas-de-intervencion/adolescentes/ansiedad-adolescente'], faqs: faq('ansiedad adulta', ['¿La ansiedad se quita rápido?', 'No prometo plazos. Sí trabajo con dirección y revisando qué ayuda en tu caso.', '¿Y si los síntomas son físicos?', 'Conviene descartar causas médicas cuando procede y, a la vez, mirar la parte emocional.', '¿Tengo que saber el origen?', 'No siempre al principio. Podemos empezar por cómo funciona ahora.', '¿Se trabaja con EMDR?', 'Solo si la evaluación indica que experiencias previas están implicadas y tiene sentido clínico.']) }),
  page({ sector: 'adults', slug: 'estres', label: 'Estrés adultos', h1: 'Estrés en adultos', title: 'Estrés en adultos en Ciudad Real | Hilando Fino Psicología', description: 'Trabajo el estrés atendiendo a carga, límites, cuerpo, descanso, decisiones y responsabilidades sostenidas.', summary: 'Estrés adulto como sobrecarga, límites, descanso, cuerpo, trabajo, familia y responsabilidad sostenida.', audience: 'el estrés', group: 'stress-adult', opening: 'Trabajo el estrés mirando la carga real que sostienes y la forma en que tu cuerpo intenta avisar. No todo es falta de organización: a veces hay demasiada responsabilidad, poco descanso y límites muy difíciles de poner.', signs: ['cansancio persistente', 'irritabilidad', 'sensación de no llegar', 'dificultad para desconectar'], impact: 'El estrés puede ocupar trabajo, familia, pareja, sueño y decisiones cotidianas. También puede confundirse con ansiedad cuando la carga se mantiene demasiado tiempo.', help: 'Te acompaño a diferenciar urgencia real, exigencia interna, límites, descanso y decisiones. El objetivo no es rendir más, sino vivir con más claridad y menos sobrecarga.', process: 'Podemos revisar mapa de cargas, recursos, prioridades, cuerpo, comunicación de límites y cambios posibles sin negar las condiciones reales de tu vida.', relatedPaths: ['/areas-de-intervencion/adultos/ansiedad', '/areas-de-intervencion/adultos/crecimiento-personal', '/areas-de-intervencion/adultos/relaciones-de-pareja'], faqs: faq('estrés adulto', ['¿Estrés y ansiedad son lo mismo?', 'Se parecen, pero el estrés suele estar más ligado a carga y contexto. Aun así pueden mezclarse.', '¿Tengo que cambiarlo todo?', 'No. Primero ordenamos qué es modificable, qué necesita límite y qué requiere apoyo.', '¿Puede afectar al cuerpo?', 'Sí. Tensión, sueño, digestión o cansancio pueden formar parte del cuadro, sin olvidar valoración médica si procede.', '¿Es terapia o coaching?', 'Trabajo desde psicología, no desde promesas de productividad.']) }),
  page({ sector: 'adults', slug: 'trauma', label: 'Trauma adultos', h1: 'Trauma en adultos', title: 'Trauma en adultos en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño trauma en adultos con evaluación cuidadosa, seguridad, ritmo y trabajo integrador cuando tiene sentido.', summary: 'Trauma adulto con seguridad, historia, cuerpo, vínculos y EMDR solo como posible herramienta tras evaluación.', audience: 'una experiencia traumática', group: 'trauma-adult', opening: 'Acompaño trauma en adultos sin empujar el relato. Me importa construir seguridad, entender qué sigue activo en el presente y elegir un ritmo que no vuelva a sobrepasarte.', signs: ['recuerdos intrusivos', 'hipervigilancia', 'bloqueo o desconexión', 'dificultad para confiar o poner límites'], impact: 'El trauma puede aparecer en el cuerpo, en la relación con otras personas, en la forma de dormir, decidir o sentir seguridad. A veces se vive como si el pasado siguiera presente.', help: 'Trabajo desde una mirada integradora. EMDR puede ser una herramienta posible, pero solo después de valorar estabilidad, recursos, vínculo terapéutico y objetivo de trabajo.', process: 'El proceso puede empezar por estabilización, recursos corporales, comprensión de la historia, trabajo con recuerdos cuando procede y revisión de vínculos y límites.', relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/adultos/duelo', '/areas-de-intervencion/adultos/ansiedad'], boundaries: [{ kind: 'emergency', text: 'Si hay violencia activa, riesgo inmediato o desprotección, la prioridad es seguridad y recursos de emergencia.' }], faqs: faq('trauma adulto', ['¿Tengo que contarlo todo?', 'No. Primero construimos seguridad y acordamos ritmo.', '¿EMDR sirve siempre?', 'No es universal. Lo valoro dentro de una evaluación y un encuadre cuidadoso.', '¿Puede aparecer como ansiedad?', 'Sí. La alarma, el cuerpo o la evitación pueden estar conectados con experiencias previas.', '¿Y si no sé si fue trauma?', 'Podemos mirar el impacto sin forzar una etiqueta.']) }),
  page({ sector: 'adults', slug: 'duelo', label: 'Duelo adultos', h1: 'Duelo en adultos', title: 'Duelo en adultos en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño el duelo sin imponer tiempos ni frases hechas, atendiendo a la pérdida y a la vida que cambia.', summary: 'Duelo adulto con pérdida, vínculo, roles, culpa, ambivalencia, tiempo y vida cotidiana.', audience: 'el duelo', group: 'grief-adult', opening: 'Acompaño el duelo en adultos sin imponer calendarios. Una pérdida puede traer tristeza, rabia, culpa, alivio, cansancio o una sensación extraña de seguir funcionando por fuera.', signs: ['dolor que desborda', 'culpa o ambivalencia', 'dificultad para retomar rutinas', 'sensación de haber perdido una parte de la vida'], impact: 'El duelo cambia roles, casa, cuerpo, relaciones y proyectos. A veces lo difícil no es solo la ausencia, sino la vida que queda reorganizada alrededor de ella.', help: 'Trabajo contigo para dar lugar a la pérdida y también a lo que sigue vivo. No busco que olvides, sino que puedas encontrar una forma propia de sostener el vínculo y continuar.', process: 'El proceso puede incluir relato de la pérdida, trabajo con culpa, cuerpo, rituales, relación con la persona perdida y decisiones que aparecen después.', relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/adultos/trauma', '/areas-de-intervencion/adultos/crecimiento-personal'], faqs: faq('duelo adulto', ['¿Cuánto dura un duelo?', 'No hay duración única. Miro cómo impacta, qué apoyos hay y qué necesita ser elaborado.', '¿Es normal sentir alivio?', 'Sí puede serlo. El duelo no siempre es una emoción pura o sencilla.', '¿Tengo que hablar de la persona perdida?', 'Solo al ritmo que puedas. También se puede empezar por cómo estás viviendo ahora.', '¿Cuándo pedir ayuda?', 'Cuando el dolor bloquea la vida, se vuelve muy solitario o aparecen señales de riesgo.']) }),
  page({ sector: 'adults', slug: 'dependencia-emocional', label: 'Dependencia emocional', h1: 'Dependencia emocional', title: 'Dependencia emocional en Ciudad Real | Hilando Fino Psicología', description: 'Trabajo la dependencia emocional mirando vínculo, miedo, autoestima, límites y patrones aprendidos.', summary: 'Dependencia emocional desde miedo, apego, límites, autoestima, historia vincular y seguridad.', audience: 'la dependencia emocional', group: 'dependence-adult', opening: 'Trabajo la dependencia emocional sin juzgar ni reducirla a “falta de voluntad”. Me interesa comprender qué miedo se activa en el vínculo, qué historia hay detrás y qué límites resultan difíciles de sostener.', signs: ['miedo intenso a la ruptura', 'renuncia constante a necesidades propias', 'dificultad para poner límites', 'ansiedad ante distancia o silencio'], impact: 'La dependencia emocional puede estrechar la vida, aislar de apoyos, deteriorar autoestima y convertir la relación en el centro absoluto de seguridad.', help: 'Te acompaño a mirar apego, autoestima, límites, culpa, deseo y patrones repetidos. No empujo decisiones; trabajo para que puedas escucharte con más libertad y seguridad.', process: 'El proceso puede incluir mapa de vínculos, regulación de ansiedad, límites graduales, historia relacional y diferenciación entre cuidado, miedo y control.', relatedPaths: ['/areas-de-intervencion/adultos/relaciones-de-pareja', '/areas-de-intervencion/adultos/ansiedad', '/areas-de-intervencion/adultos/crecimiento-personal'], boundaries: [{ kind: 'safety', text: 'Si hay coerción, violencia, amenazas o control grave, la prioridad es seguridad y recursos especializados; la terapia no sustituye protección.' }], faqs: faq('dependencia emocional', ['¿Tengo que dejar la relación?', 'No parto de una decisión cerrada. Trabajo para que puedas pensar con más claridad y seguridad.', '¿Es amor o miedo?', 'A veces están mezclados. Podemos mirar qué parte sostiene y qué parte te deja sin libertad.', '¿Se trabaja autoestima?', 'Sí, junto con límites, historia vincular y regulación de la ansiedad.', '¿Y si hay violencia?', 'Entonces la prioridad es seguridad, apoyo especializado y recursos adecuados.']) }),
  page({ sector: 'adults', slug: 'relaciones-de-pareja', label: 'Relaciones de pareja', h1: 'Relaciones de pareja', title: 'Relaciones de pareja en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño dificultades de pareja mirando comunicación, conflicto, necesidades, historia vincular y límites.', summary: 'Relaciones de pareja desde comunicación, conflicto, apego, límites y seguridad sin prometer formato no confirmado.', audience: 'una dificultad de pareja', group: 'couple-adult', opening: 'Acompaño dificultades de pareja mirando qué se repite en la comunicación, qué necesidades quedan sin decir y qué límites se han ido desdibujando. No reduzco el vínculo a quién tiene razón.', signs: ['discusiones circulares', 'distancia emocional', 'celos o control', 'dudas sobre continuar o cambiar la relación'], impact: 'Una dificultad de pareja puede afectar descanso, autoestima, deseo, vida familiar y sensación de seguridad. A veces el conflicto actual toca heridas anteriores.', help: 'Trabajo para comprender patrones, comunicación, apego, límites y responsabilidad personal. El formato concreto debe ajustarse a lo confirmado y a la seguridad de cada situación.', process: 'El proceso puede centrarse en trabajo individual sobre el vínculo o valorar otro encuadre si procede. Si hay violencia o coerción, no planteo la terapia como solución suficiente.', relatedPaths: ['/areas-de-intervencion/adultos/dependencia-emocional', '/areas-de-intervencion/adultos/crecimiento-personal', '/areas-de-intervencion/adultos/estres'], boundaries: [{ kind: 'safety', text: 'Ante violencia, amenazas o control coercitivo, la prioridad es protección y recursos especializados; no basta con mejorar comunicación.' }, { kind: 'scope', text: 'No afirmo formato de terapia de pareja hasta que Marta confirme el encuadre ofrecido.' }], faqs: faq('relaciones de pareja', ['¿Es terapia de pareja?', 'No afirmo un formato no confirmado. Puedo orientar dificultades vinculares desde un encuadre prudente.', '¿Cuándo no conviene terapia conjunta?', 'Cuando hay violencia, miedo o coerción, la seguridad va antes que la conversación conjunta.', '¿Se puede trabajar individualmente?', 'Sí, muchas dinámicas vinculares pueden pensarse desde el proceso individual.', '¿Y si no sé qué decisión tomar?', 'Podemos trabajar claridad, límites y necesidades sin empujarte a una decisión rápida.']) }),
  page({ sector: 'adults', slug: 'crecimiento-personal', label: 'Crecimiento personal', h1: 'Crecimiento personal', title: 'Crecimiento personal en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño procesos de autoconocimiento, responsabilidad, deseo y coherencia con la propia vida.', summary: 'Crecimiento personal sin coaching milagroso: autoconocimiento, valores, límites, deseo y decisiones.', audience: 'un proceso de crecimiento personal', group: 'growth-adult', opening: 'Acompaño crecimiento personal cuando no hay una crisis clara, pero sí una pregunta insistente sobre cómo estás viviendo. No lo planteo como transformación rápida, sino como autoconocimiento con responsabilidad.', signs: ['sensación de vivir en automático', 'dudas sobre decisiones importantes', 'necesidad de límites', 'deseo de conocerte mejor sin esperar a tocar fondo'], impact: 'A veces el malestar no aparece como síntoma intenso, sino como distancia con una misma, decisiones aplazadas o dificultad para reconocer deseos y límites.', help: 'Trabajo contigo para escuchar valores, historia, cuerpo, vínculos y elecciones. Me interesa que el proceso tenga dirección, no frases bonitas.', process: 'El proceso puede incluir exploración de patrones, decisiones, límites, proyecto vital y coherencia entre lo que necesitas y lo que sostienes cada día.', relatedPaths: ['/areas-de-intervencion/adultos/estres', '/areas-de-intervencion/adultos/relaciones-de-pareja', '/areas-de-intervencion/adultos/duelo'], faqs: faq('crecimiento personal', ['¿Puedo ir a terapia sin una crisis?', 'Sí. No hace falta tocar fondo para mirar tu vida con más honestidad.', '¿Es coaching?', 'No lo presento como coaching ni prometo transformación. Trabajo desde psicología y proceso.', '¿Qué temas se pueden trabajar?', 'Límites, decisiones, deseo, autoestima, vínculos, etapas vitales o sentido.', '¿Cómo sé si es para mí?', 'Si hay una pregunta que vuelve y te cuesta pensarla sola, puede tener sentido consultarlo.']) }),
  page({
    sector: 'adults', slug: 'estado-de-animo', label: 'Estado de ánimo y baja energía', h1: 'Estado de ánimo y baja energía',
    title: 'Estado de ánimo bajo y falta de energía | Hilando Fino Psicología',
    description: 'Acompaño a personas adultas cuando la tristeza, la apatía o la pérdida de motivación se instalan en el día a día.',
    summary: 'Vacío, tristeza sostenida, apatía y pérdida de motivación leídos con historia, descanso, cuerpo y vínculos.',
    audience: 'una persona adulta', group: 'mood-adult',
    opening: 'Acompaño el estado de ánimo bajo cuando la tristeza deja de ser un momento y se convierte en clima. Me interesa saber desde cuándo pesa, qué se apagó primero y qué sigue sosteniéndote, aunque ahora cueste verlo.',
    signs: ['una sensación de vacío difícil de nombrar', 'tristeza profunda que el descanso no alivia', 'apatía ante lo que antes ilusionaba', 'pérdida de motivación en el día a día'],
    impact: 'Cuando el ánimo baja, el cuerpo avisa antes que las palabras: cuesta arrancar, el sueño se descoloca, el apetito cambia y las tareas más pequeñas empiezan a parecer cuesta arriba. La vida social se estrecha y aparece culpa por no rendir como antes.',
    help: 'Trabajo contigo para distinguir qué parte es agotamiento acumulado, qué parte es una pérdida sin elaborar, qué parte es autoexigencia sostenida y qué parte merece además una valoración médica. Buscamos recuperar actividad y sentido a un ritmo sostenible, sin exigirte entusiasmo.',
    process: 'El acompañamiento puede incluir revisión del descanso y las rutinas, activación gradual, trabajo con la autoexigencia, exploración de pérdidas previas y coordinación con tu médico si conviene valorar el plano físico o farmacológico.',
    relatedPaths: ['/areas-de-intervencion/adultos/ansiedad', '/areas-de-intervencion/adultos/duelo', '/areas-de-intervencion/adultos/estres'],
    boundaries: [
      { kind: 'medical', text: 'Un ánimo bajo sostenido también puede tener causas físicas (tiroides, anemia, déficits o efectos de medicación). Conviene valorarlo con tu médico además de trabajar la parte emocional.' },
      { kind: 'emergency', text: 'Si aparecen ideas de hacerte daño o de no querer seguir viviendo, no esperes a una cita: llama al 024, al 112 o acude a urgencias.' }
    ],
    faqs: faq('el ánimo bajo', ['¿Esto es depresión?', 'Poner nombre no es lo primero. Prefiero mirar intensidad, duración, impacto y qué lo sostiene antes de usar una etiqueta.', '¿Y si no tengo un motivo claro?', 'No siempre hay un desencadenante visible. A veces es una suma lenta de cansancio, exigencia y pérdidas pequeñas.', '¿Tengo que estar de baja para consultar?', 'No. Muchas personas sostienen su rutina entera mientras por dentro todo pesa el doble.', '¿Se combina con tratamiento médico?', 'Puede combinarse. Si ya tomas medicación o la estás valorando, trabajamos de forma coordinada con quien la prescribe.'])
  }),
  page({
    sector: 'perinatal', slug: 'transicion-vital-y-maternidades', label: 'Transición vital y maternidades', h1: 'Transición vital y maternidades',
    title: 'Transición a la maternidad e identidad | Hilando Fino Psicología',
    description: 'Acompaño la redefinición de la identidad al asumir la crianza y también al transitar la decisión o la circunstancia de no ser madre.',
    summary: 'Identidad, deseo y renuncia en la transición a la maternidad, incluida la maternidad que no llega o que no se elige.',
    audience: 'quien atraviesa esta transición', group: 'perinatal-identity',
    opening: 'Acompaño la redefinición de tu identidad tanto al asumir la crianza como al transitar la decisión o la circunstancia de no ser madre. Convertirse en madre, o elegir no serlo, reordena el deseo, el tiempo, el oficio y los vínculos, y ese reordenamiento merece un espacio propio.',
    signs: ['la sensación de no reconocerte desde que nació tu hijo', 'una ambivalencia que da vergüenza nombrar', 'nostalgia de la vida anterior', 'presión del entorno ante la decisión de no ser madre'],
    impact: 'La llegada de un hijo se narra casi siempre como celebración, y esa narrativa deja poco margen para lo que también se pierde: el oficio que se frena, el cuerpo que cambia, la pareja que se reorganiza, la amistad que se distancia. Cuando eso no se puede decir, la ambivalencia se vive como defecto propio.',
    help: 'Trabajo contigo para poner palabras a lo que convive sin contradicción: querer muchísimo a tu hijo y echar de menos quien eras. También acompaño la otra orilla, la de quien no será madre por elección o por circunstancia, sin tratarla como una biografía incompleta.',
    process: 'Podemos revisar expectativas propias y heredadas, mandatos familiares, reparto de cuidados, tiempo propio y la conversación con la pareja o el entorno cuando la decisión se cuestiona desde fuera.',
    relatedPaths: ['/areas-de-intervencion/psicologia-perinatal/salud-emocional-posparto', '/areas-de-intervencion/psicologia-perinatal/procesos-de-fertilidad', '/areas-de-intervencion/adultos/crecimiento-personal'],
    faqs: faq('la transición a la maternidad', ['¿Es normal arrepentirse a ratos?', 'La ambivalencia es frecuente y no dice nada malo de ti. Callarla es lo que suele doler más.', '¿Puedo consultar si decido no ser madre?', 'Sí. Esa decisión también reordena identidad, pareja y relación con la propia familia.', '¿Cuándo conviene pedir ayuda?', 'Cuando la sensación de haberte perdido lleva meses y el entorno insiste en que deberías estar plena.', '¿Se trabaja con la pareja?', 'Puede incluirse si el reparto de cuidados o las expectativas están tensando la relación.'])
  }),
  page({
    sector: 'perinatal', slug: 'vinculo-temprano-y-apego-seguro', label: 'Vínculo temprano y apego seguro', h1: 'Vínculo temprano y apego seguro',
    title: 'Vínculo con el bebé y apego seguro | Hilando Fino Psicología',
    description: 'Acompaño la construcción de una conexión sólida con tu bebé desde la presencia, la sintonía corporal y el afecto.',
    summary: 'Apego seguro en los primeros meses: lectura de señales, contacto, sintonía corporal y capacidad de reparar.',
    audience: 'una madre o un padre reciente', group: 'perinatal-attachment',
    opening: 'Te acompaño a construir una conexión sólida con tu bebé desde la presencia, la sintonía corporal y el afecto. El apego seguro no se instala de golpe ni exige acertar siempre: se teje en gestos mínimos y, sobre todo, en la capacidad de reparar cuando algo se desajusta.',
    signs: ['dificultad para interpretar el llanto', 'la impresión de no estar conectando con tu bebé', 'miedo a equivocarte en cada decisión', 'comparación constante con otras crianzas'],
    impact: 'Los primeros meses concentran agotamiento extremo, opiniones ajenas y una exigencia enorme de intuición inmediata. Cuando la sintonía cuesta aparece culpa, y la culpa aleja todavía más de la escucha tranquila que ese bebé necesita.',
    help: 'Trabajo contigo la lectura de señales, el contacto, el ritmo de los cuidados y tu propia regulación como adulto, apoyándome en modelos de apego como el Círculo de Seguridad Parental. Me interesa que confíes en tu lectura, no que sigas un manual.',
    process: 'El acompañamiento puede incluir observación de las rutinas de cuidado, trabajo corporal y respiratorio, revisión de tu propia historia de apego y espacio para la pareja o la red que os sostiene.',
    relatedPaths: ['/areas-de-intervencion/psicologia-perinatal/salud-emocional-posparto', '/areas-de-intervencion/infancia-y-familias/regulacion-emocional-infantil', '/areas-de-intervencion/psicologia-perinatal/transicion-vital-y-maternidades'],
    boundaries: [{ kind: 'pediatric', text: 'Si tienes dudas sobre alimentación, peso, desarrollo o salud del bebé, la valoración de pediatría y de tu matrona es prioritaria.' }],
    faqs: faq('el vínculo temprano', ['¿Y si no siento el flechazo del que todos hablan?', 'Es más común de lo que se cuenta. El vínculo suele construirse despacio, no aparecer entero el primer día.', '¿El apego seguro depende de hacerlo todo bien?', 'No. Depende mucho más de reparar los desencuentros que de evitarlos.', '¿Puede venir el padre o la otra figura de crianza?', 'Sí, y suele ayudar: el vínculo se sostiene mejor cuando ambos leen las mismas señales.', '¿Sirve si mi bebé ya tiene un año?', 'Sí. El apego se sigue construyendo mucho después de los primeros meses.'])
  }),
  page({
    sector: 'perinatal', slug: 'salud-emocional-posparto', label: 'Salud emocional en el posparto', h1: 'Salud emocional en el posparto',
    title: 'Ansiedad y tristeza en el posparto | Hilando Fino Psicología',
    description: 'Atiendo la ansiedad, la sobrecarga o la tristeza tras el nacimiento para recuperar estabilidad y equilibrio en el día a día.',
    summary: 'Ansiedad, sobrecarga y tristeza posparto atendidas con descanso, red de apoyo, cuerpo y frontera clínica clara.',
    audience: 'una mujer recién parida', group: 'perinatal-postpartum',
    opening: 'Atiendo la ansiedad, la sobrecarga y la tristeza que pueden aparecer tras el nacimiento. El posparto se cuenta como una etapa luminosa, y cuando lo que sientes no encaja con esa imagen resulta fácil callarlo. Aquí no hace falta que encaje.',
    signs: ['llanto frecuente sin motivo claro', 'angustia que aparece de madrugada', 'pensamientos intrusivos que asustan', 'la impresión de estar fallando a todo el mundo'],
    impact: 'El posparto reúne privación de sueño, cambio hormonal, herida física, lactancia y una identidad recién estrenada. Ese conjunto agota la capacidad de regularse, tensa la pareja y hace que pedir ayuda parezca la confesión de un fracaso.',
    help: 'Trabajo contigo el descanso posible, la red de apoyo real, la exigencia interna y los pensamientos que más asustan, distinguiendo lo que forma parte de una adaptación difícil de lo que necesita además valoración clínica.',
    process: 'Podemos revisar sueño, alimentación, reparto de cuidados, lactancia y vuelta al empleo, sumando trabajo corporal para bajar la activación cuando el cuerpo no encuentra la calma por sí solo.',
    relatedPaths: ['/areas-de-intervencion/psicologia-perinatal/vinculo-temprano-y-apego-seguro', '/areas-de-intervencion/adultos/ansiedad', '/areas-de-intervencion/psicologia-perinatal/transicion-vital-y-maternidades'],
    boundaries: [
      { kind: 'medical', text: 'Si la tristeza, la angustia o los pensamientos intrusivos son intensos o llevan semanas instalados, conviene una valoración clínica: la depresión posparto tiene tratamiento y no se resuelve a base de voluntad.' },
      { kind: 'emergency', text: 'Ante ideas de hacerte daño o de dañar al bebé, contacta de inmediato con el 112, con el 024 o acude a urgencias.' }
    ],
    faqs: faq('el posparto', ['¿Cuánto dura la tristeza normal tras el parto?', 'Los primeros días de labilidad son habituales. Si se alarga varias semanas o va a más, conviene mirarlo con calma.', '¿Los pensamientos intrusivos significan que soy peligrosa?', 'Casi nunca. Suelen ser imágenes angustiosas y egodistónicas, pero merecen hablarse en lugar de esconderse.', '¿Puedo venir con el bebé?', 'Podemos organizarlo. Lo importante es que puedas acudir, no que resuelvas antes la logística perfecta.', '¿Y si ya pasó el primer año?', 'Sigue teniendo sentido. Hay pospartos que se elaboran mucho después.'])
  }),
  page({
    sector: 'perinatal', slug: 'gestacion-y-preparacion-al-parto', label: 'Gestación serena y preparación al parto', h1: 'Gestación serena y preparación al parto',
    title: 'Miedo al parto y apoyo emocional en el embarazo | Hilando Fino',
    description: 'Trabajo emocional y corporal para regular el miedo, calmar el sistema nervioso y afrontar el parto con mayor confianza.',
    summary: 'Embarazo y parto trabajados desde el miedo, la respiración, el sistema nervioso y las experiencias previas.',
    audience: 'una mujer embarazada', group: 'perinatal-pregnancy',
    opening: 'Trabajo el plano emocional y corporal de la gestación para regular el miedo, calmar el sistema nervioso y afrontar el parto con mayor confianza. Cuando hay un parto anterior difícil, ese recuerdo suele estar mucho más presente de lo que se dice en voz alta.',
    signs: ['miedo intenso al dolor o a las complicaciones', 'recuerdos de un parto anterior que vuelven solos', 'dificultad para conectar con la gestación', 'insomnio o hipervigilancia en el tercer trimestre'],
    impact: 'El miedo sostenido durante el embarazo mantiene el cuerpo en alerta, altera el descanso y termina condicionando cómo se vive la propia gestación. También dificulta expresar con claridad qué deseas y qué temes en el momento del nacimiento.',
    help: 'Trabajo contigo la respiración, la conciencia corporal y la regulación del sistema nervioso, junto con el relato de experiencias anteriores. Si un parto previo dejó huella traumática, valoramos si tiene sentido abordarlo con EMDR antes de la fecha.',
    process: 'El acompañamiento puede incluir ejercicios corporales, trabajo con la anticipación, ordenar tus preferencias para el nacimiento y la conversación con tu pareja sobre cómo quieres sentirte acompañada ese día.',
    relatedPaths: ['/areas-de-intervencion/psicologia-perinatal/duelo-perinatal', '/areas-de-intervencion/psicologia-perinatal/vinculo-temprano-y-apego-seguro', '/areas-de-intervencion/adultos/trauma'],
    boundaries: [{ kind: 'medical', text: 'El acompañamiento psicológico complementa, y nunca sustituye, el seguimiento de matrona, ginecología y obstetricia durante el embarazo y el parto.' }],
    faqs: faq('el miedo al parto', ['¿Es tarde si estoy de ocho meses?', 'No. Incluso pocas semanas dan margen para trabajar respiración, anticipación y miedo.', '¿Sirve si mi primer parto fue traumático?', 'Sí, y suele ser uno de los motivos más frecuentes. Se valora con cuidado antes de abordar el recuerdo.', '¿Esto sustituye a las clases de matrona?', 'No. Son complementarias: allí se aprende el plano fisiológico, aquí se trabaja el emocional.', '¿Puede venir mi pareja?', 'Sí, sobre todo para acordar cómo quieres ser acompañada durante el nacimiento.'])
  }),
  page({
    sector: 'perinatal', slug: 'procesos-de-fertilidad', label: 'Acompañamiento en fertilidad', h1: 'Acompañamiento en procesos de fertilidad',
    title: 'Apoyo psicológico en fertilidad y reproducción asistida | Hilando Fino',
    description: 'Sostén emocional ante la incertidumbre, el desgaste y las decisiones que acompañan a los tratamientos de reproducción asistida.',
    summary: 'Fertilidad y reproducción asistida sostenidas en la incertidumbre, el desgaste de los ciclos y las decisiones de pareja.',
    audience: 'quien atraviesa un tratamiento de fertilidad', group: 'perinatal-fertility',
    opening: 'Sostengo el plano emocional de los procesos de fertilidad: la incertidumbre, el desgaste acumulado y las decisiones difíciles que traen los tratamientos de reproducción asistida. Es un camino largo que casi nunca avanza en línea recta.',
    signs: ['la vida organizada alrededor de ciclos y esperas', 'agotamiento después de varios intentos', 'dificultad para estar cerca de embarazos ajenos', 'desacuerdos con tu pareja sobre hasta dónde llegar'],
    impact: 'La fertilidad convierte la intimidad en calendario y la esperanza en un ciclo que se abre y se cierra cada pocas semanas. El cuerpo se somete a tratamientos exigentes mientras el entorno pregunta con ligereza, y el desgaste se acumula en silencio.',
    help: 'Trabajo contigo la tolerancia a la incertidumbre, el duelo de cada intento que no sale, la comunicación con tu pareja y los límites que quieres poner al recorrido, incluida la pregunta de cuándo parar.',
    process: 'Podemos sostener las esperas, ordenar las decisiones antes de tomarlas, cuidar la relación de pareja durante el tratamiento y revisar tu relación con el cuerpo cuando empieza a sentirse solo como un instrumento médico.',
    relatedPaths: ['/areas-de-intervencion/psicologia-perinatal/duelo-perinatal', '/areas-de-intervencion/psicologia-perinatal/transicion-vital-y-maternidades', '/areas-de-intervencion/adultos/relaciones-de-pareja'],
    boundaries: [{ kind: 'medical', text: 'No intervengo en diagnósticos, pronósticos ni decisiones médicas del tratamiento: esas corresponden a tu equipo de reproducción asistida.' }],
    faqs: faq('los procesos de fertilidad', ['¿Cuándo conviene empezar?', 'No hace falta esperar a estar al límite. Empezar antes suele hacer el recorrido más llevadero.', '¿Se puede acudir en pareja?', 'Sí. Es frecuente que cada persona viva el proceso a distinta velocidad y eso genere distancia.', '¿Y si decidimos parar?', 'Parar también es una decisión legítima y necesita ser acompañada, no solo ejecutada.', '¿Ayuda el trabajo corporal?', 'Puede ayudar a bajar la activación, aunque no planteo ninguna técnica como forma de aumentar la fertilidad.'])
  }),
  page({
    sector: 'perinatal', slug: 'duelo-perinatal', label: 'Duelo perinatal', h1: 'Elaboración del duelo perinatal',
    title: 'Duelo perinatal y pérdida gestacional | Hilando Fino Psicología',
    description: 'Un lugar de profundo respeto para nombrar, sostener y procesar la pérdida gestacional o neonatal en cualquier etapa.',
    summary: 'Pérdida gestacional o neonatal acompañada con respeto, sin plazos, sin jerarquías de dolor y sin frases hechas.',
    audience: 'una familia que ha perdido un bebé', group: 'perinatal-loss',
    opening: 'Ofrezco un lugar de profundo respeto para nombrar, sostener y procesar la pérdida gestacional o neonatal en cualquier etapa. No mido el dolor por semanas de gestación ni pido que la pérdida se justifique para poder acompañarla.',
    signs: ['un dolor que el entorno minimiza por lo temprano de la pérdida', 'silencio alrededor del bebé que no llegó', 'culpa buscando una causa', 'miedo intenso ante un nuevo embarazo'],
    impact: 'El duelo perinatal es una pérdida sin apenas recuerdos compartidos, y eso deja a la familia sin los rituales que sostienen otros duelos. Alrededor se instala un silencio bienintencionado que suele aumentar la soledad en lugar de aliviarla.',
    help: 'Trabajo contigo el relato de lo ocurrido a tu ritmo, el lugar que quieres darle a tu bebé, la culpa y la relación de pareja, donde cada persona suele atravesarlo de forma muy distinta y a distinta velocidad.',
    process: 'El acompañamiento puede incluir espacio para nombrar y recordar, gestos o rituales que tengan significado para vosotros, la vuelta al entorno social y, si la vivencia dejó huella traumática, valorar EMDR tras una evaluación cuidadosa.',
    relatedPaths: ['/psicologia-trauma-ciudad-real', '/areas-de-intervencion/psicologia-perinatal/gestacion-y-preparacion-al-parto', '/areas-de-intervencion/adultos/duelo'],
    boundaries: [
      { kind: 'emergency', text: 'Si el dolor se vuelve insoportable y aparecen ideas de no querer seguir viviendo, busca ayuda inmediata en el 024, el 112 o en urgencias.' },
      { kind: 'medical', text: 'Acompaño el proceso emocional; el seguimiento médico de la pérdida y de un posible embarazo posterior corresponde a tu equipo sanitario.' }
    ],
    faqs: faq('el duelo perinatal', ['¿Cuenta como duelo si fue muy pronto?', 'Sí. El vínculo empieza mucho antes del nacimiento y la pérdida no se mide en semanas.', '¿Es normal que mi pareja lo viva distinto?', 'Es muy frecuente, y ese desfase suele doler tanto como la pérdida misma.', '¿Puedo consultar años después?', 'Sí. Hay duelos perinatales que se guardan durante años y reaparecen con un nuevo embarazo.', '¿Se habla del bebé por su nombre?', 'Si vosotros queréis, sí. Nombrarlo suele formar parte de poder sostenerlo.'])
  }),
  page({ sector: 'education-training', slug: 'dificultades-de-aprendizaje', label: 'Dificultades de aprendizaje', h1: 'Dificultades de aprendizaje', title: 'Dificultades de aprendizaje en Ciudad Real | Hilando Fino', description: 'Acompaño a familias cuando aprender se vuelve difícil y hace falta mirar emoción, escuela, recursos y coordinación.', summary: 'Aprendizaje leído con emoción, familia, escuela, recursos y límites de evaluación/diagnóstico.', audience: 'aprender', group: 'learning-education', opening: 'Acompaño dificultades de aprendizaje mirando más que el rendimiento. Cuando aprender se vuelve difícil, también hay emoción, autoestima, familia, escuela y recursos disponibles.', signs: ['bloqueo ante lectura o escritura', 'tareas que se hacen eternas', 'frustración con deberes', 'sensación de no poder aunque se esfuerce'], impact: 'La dificultad para aprender puede afectar confianza, relación con el colegio, clima en casa y motivación. Si se interpreta como pereza, el niño puede quedarse más solo.', help: 'Te acompaño a ordenar qué puede estar influyendo y qué apoyos tienen sentido, sin hacer afirmaciones diagnósticas no verificadas ni prometer informes no confirmados.', process: 'El proceso puede incluir recogida de información familiar y escolar, revisión de apoyos, coordinación con el centro y derivación a evaluación específica si hace falta.', relatedPaths: ['/areas-de-intervencion/orientacion-educativa-y-formacion/coordinacion-centros-educativos', '/areas-de-intervencion/infancia-y-familias/dificultades-escolares', '/areas-de-intervencion/orientacion-educativa-y-formacion/altas-capacidades'], boundaries: [{ kind: 'scope', text: 'No afirmo diagnóstico, pruebas o informes específicos hasta que el alcance profesional esté confirmado.' }], faqs: faq('dificultades de aprendizaje', ['¿Es falta de esfuerzo?', 'No parto de esa idea. Miro recursos, emoción, método, contexto y posibles necesidades específicas.', '¿Se hacen diagnósticos?', 'No afirmo servicios diagnósticos no confirmados. Puedo orientar y derivar cuando corresponde.', '¿Debe participar el colegio?', 'Suele ayudar si hay consentimiento y objetivo claro.', '¿Cómo afecta a la autoestima?', 'Mucho. La vivencia de “no puedo” puede pesar tanto como la dificultad concreta.']) }),
  page({ sector: 'education-training', slug: 'altas-capacidades', label: 'Altas capacidades', h1: 'Altas capacidades', title: 'Altas capacidades en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño a familias cuando las altas capacidades conviven con sensibilidad, aburrimiento, exigencia o desajustes.', summary: 'Altas capacidades con sensibilidad, aburrimiento, desajuste, exigencia, escuela y fronteras de evaluación.', audience: 'una consulta por altas capacidades', group: 'high-abilities-education', opening: 'Acompaño a familias cuando las altas capacidades conviven con sensibilidad, aburrimiento, exigencia o desajuste. No lo miro como una etiqueta brillante, sino como una forma compleja de vivir y aprender.', signs: ['aburrimiento intenso en clase', 'perfeccionismo', 'sensibilidad emocional', 'desajuste entre capacidad y bienestar'], impact: 'Cuando el entorno no entiende bien estas necesidades, pueden aparecer conflictos, aislamiento, baja motivación o una exigencia interna difícil de sostener.', help: 'Te acompaño a mirar emoción, escuela, familia y expectativas. Si hace falta evaluación específica, lo valoro con prudencia y sin prometer pruebas no confirmadas.', process: 'El proceso puede incluir orientación familiar, lectura del contexto escolar, coordinación con el centro y cuidado de autoestima, sensibilidad y límites.', relatedPaths: ['/areas-de-intervencion/orientacion-educativa-y-formacion/dificultades-de-aprendizaje', '/areas-de-intervencion/orientacion-educativa-y-formacion/coordinacion-centros-educativos', '/areas-de-intervencion/infancia-y-familias/autoestima-infantil'], boundaries: [{ kind: 'scope', text: 'No afirmo evaluación diagnóstica de altas capacidades hasta que el servicio, pruebas y competencias estén confirmados.' }], faqs: faq('altas capacidades', ['¿Altas capacidades siempre significa buen rendimiento?', 'No. Puede haber aburrimiento, bloqueo, sensibilidad o desajuste escolar.', '¿Se realizan pruebas?', 'No afirmo pruebas no confirmadas. Si son necesarias, puedo orientar el siguiente paso.', '¿Puede haber malestar emocional?', 'Sí. Capacidad y bienestar no siempre van juntos.', '¿Cómo participa el centro?', 'La coordinación puede ayudar si hay consentimiento y objetivos concretos.']) }),
  page({ sector: 'education-training', slug: 'coordinacion-centros-educativos', label: 'Coordinación con centros educativos', h1: 'Coordinación con centros educativos', title: 'Coordinación con centros educativos en Ciudad Real | Hilando Fino', description: 'Cuando ayuda, puedo coordinar lenguaje, expectativas y apoyos entre familia y centro educativo.', summary: 'Coordinación escuela-familia-profesional con consentimiento, privacidad, objetivos y lenguaje común.', audience: 'la coordinación entre familia y centro educativo', group: 'coordination-education', opening: 'Acompaño la coordinación con centros educativos cuando puede ayudar a que familia y escuela hablen un lenguaje más común. No se trata de intervenir por intervenir, sino de alinear apoyos con cuidado.', signs: ['mensajes contradictorios entre casa y aula', 'necesidad de adaptar apoyos', 'dudas sobre cómo comunicar una dificultad', 'situaciones escolares que afectan al bienestar'], impact: 'Cuando cada adulto interpreta algo distinto, el niño o adolescente puede quedar en medio. Una coordinación bien planteada reduce ruido y aclara responsabilidades.', help: 'Puedo ayudarte a definir qué conviene compartir, con quién, para qué y bajo qué consentimiento. La privacidad no es un trámite: forma parte del cuidado.', process: 'El proceso puede incluir objetivos de coordinación, preparación de mensajes, reunión o contacto con el centro si procede y revisión de acuerdos útiles para casa y escuela.', relatedPaths: ['/areas-de-intervencion/orientacion-educativa-y-formacion/dificultades-de-aprendizaje', '/areas-de-intervencion/adolescentes/orientacion-academica-adolescentes', '/areas-de-intervencion/orientacion-educativa-y-formacion/asesoramiento-familiar'], boundaries: [{ kind: 'consent', text: 'Toda coordinación debe tener consentimiento, objetivo claro y cuidado de la información compartida.' }], faqs: faq('coordinación con centros educativos', ['¿Siempre hace falta hablar con el centro?', 'No. Solo cuando aporta claridad y tiene un objetivo concreto.', '¿Qué información se comparte?', 'La mínima necesaria y siempre cuidando consentimiento y privacidad.', '¿Puede pedirlo la familia?', 'Sí, podemos valorar juntos si ayuda y cómo plantearlo.', '¿Sustituye al orientador del centro?', 'No. Busca coordinar, no reemplazar funciones educativas internas.']) }),
  page({ sector: 'education-training', slug: 'asesoramiento-familiar', label: 'Asesoramiento familiar', h1: 'Asesoramiento familiar', title: 'Asesoramiento familiar en Ciudad Real | Hilando Fino Psicología', description: 'Acompaño a familias que necesitan comprender necesidades, ajustar respuestas y sostener cambios en casa.', summary: 'Orientación familiar para necesidades, límites, apego, rutinas, cambios y coordinación sin prometer programa cerrado.', audience: 'la familia', group: 'family-guidance-education', opening: 'Acompaño asesoramiento familiar cuando necesitáis comprender mejor qué está pasando en casa y cómo responder con más claridad. No busco padres perfectos; busco respuestas más ajustadas y sostenibles.', signs: ['dudas sobre límites', 'conflictos repetidos', 'cambios familiares difíciles', 'necesidad de orientar la respuesta adulta'], impact: 'Cuando una familia se siente perdida, cada día puede llenarse de tensión. A veces basta con ordenar necesidades, roles y rutinas para empezar a respirar distinto.', help: 'Trabajo contigo para leer la conducta, cuidar el vínculo, sostener límites y decidir qué cambios son realistas en casa. Si hace falta otro recurso, lo nombramos.', process: 'El proceso puede incluir sesiones con adultos, momentos familiares, revisión de rutinas, lenguaje emocional y coordinación educativa si forma parte de la demanda.', relatedPaths: ['/areas-de-intervencion/infancia-y-familias/separacion-de-los-padres', '/areas-de-intervencion/infancia-y-familias/problemas-de-conducta-infantil', '/areas-de-intervencion/orientacion-educativa-y-formacion/coordinacion-centros-educativos'], boundaries: [{ kind: 'scope', text: 'No afirmo terapia familiar estructurada o programas específicos hasta que Marta confirme el alcance exacto del servicio.' }], faqs: faq('asesoramiento familiar', ['¿Pueden consultar solo los padres?', 'Sí, a veces orientar la respuesta adulta ya cambia mucho el contexto.', '¿Es terapia familiar?', 'No afirmo un formato no confirmado. Planteo orientación familiar con encuadre claro.', '¿Se trabaja con adolescentes?', 'Puede incluirse al adolescente si ayuda y se cuida su espacio propio.', '¿Qué pasa si hay conflicto entre adultos?', 'Primero miramos seguridad, comunicación y lugar de los hijos o personas implicadas.']) })
] as const;

export const treatmentPages: readonly TreatmentPage[] = baseTreatmentPages.map((item, index, all) => ({
  ...item,
  related: withSectorNeighbors(item.related, item, index, all)
}));

function faq(topic: string, pairs: string[]): FaqItem[] {
  return [0, 2, 4, 6].map((index) => ({ question: pairs[index] ?? `¿Cómo sé si ${topic} necesita acompañamiento?`, answer: pairs[index + 1] ?? 'Podemos valorarlo con calma, mirando impacto, duración, recursos y contexto.' }));
}

function list(values: string[]): string {
  if (values.length <= 1) return values[0] ?? '';
  return `${values.slice(0, -1).join(', ')} o ${values[values.length - 1]}`;
}

export function sectorPath(sector: TreatmentSector): string {
  return ({
    'children-families': 'infancia-y-familias',
    adolescents: 'adolescentes',
    adults: 'adultos',
    perinatal: 'psicologia-perinatal',
    'education-training': 'orientacion-educativa-y-formacion'
  } satisfies Record<TreatmentSector, string>)[sector];
}

function relatedLinkFor(href: string): PageCard {
  if (href === '/psicologia-trauma-ciudad-real') return traumaPillarLink;
  const label = href.split('/').at(-1)?.replace(/-/g, ' ') ?? href;
  return { title: label[0]?.toUpperCase() + label.slice(1), body: 'Página relacionada para seguir orientando la consulta con contexto específico.', href };
}

function withSectorNeighbors(related: readonly PageCard[], page: TreatmentPage, _index: number, all: readonly TreatmentPage[]): PageCard[] {
  const sameSector = all.filter((item) => item.sector === page.sector);
  const sectorIndex = sameSector.findIndex((item) => item.canonicalPath === page.canonicalPath);
  const neighbors = [sameSector[(sectorIndex + sameSector.length - 1) % sameSector.length], sameSector[(sectorIndex + 1) % sameSector.length]]
    .filter((item): item is TreatmentPage => Boolean(item) && item.canonicalPath !== page.canonicalPath)
    .map((item) => ({ title: item.h1, body: item.summary, href: item.canonicalPath }));
  const merged = [related[0], ...neighbors, ...related.slice(1)].filter((item): item is PageCard => Boolean(item));
  return merged.filter((item, itemIndex, allItems) => item.href && allItems.findIndex((candidate) => candidate.href === item.href) === itemIndex).slice(0, 6);
}
